//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_metamorphosize : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Vector2 Direction
        {
            get
            {
                return SteamVR_Actions.metamorphosize_Direction;
            }
        }
        
        public virtual SteamVR_Action_Boolean Move
        {
            get
            {
                return SteamVR_Actions.metamorphosize_Move;
            }
        }
        
        public virtual SteamVR_Action_Boolean Jump
        {
            get
            {
                return SteamVR_Actions.metamorphosize_Jump;
            }
        }
        
        public virtual SteamVR_Action_Boolean Shoot
        {
            get
            {
                return SteamVR_Actions.metamorphosize_Shoot;
            }
        }
        
        public virtual SteamVR_Action_Boolean ChangeMode
        {
            get
            {
                return SteamVR_Actions.metamorphosize_ChangeMode;
            }
        }
        
        public virtual SteamVR_Action_Boolean Grab
        {
            get
            {
                return SteamVR_Actions.metamorphosize_Grab;
            }
        }
    }
}
